// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SensoreApp.Data;

#nullable disable

namespace SensoreApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("SensoreApp.Models.SensorData", b =>
                {
                    b.Property<int>("DataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlertStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("ContactAreaPercentage")
                        .HasColumnType("REAL");

                    b.Property<int>("PeakPressureIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PressureMatrixJson")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DataId");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("SensorData");
                });

            modelBuilder.Entity("SensoreApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Role");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SensoreApp.Models.UserFeedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClinicianReply")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LinkedDataId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FeedbackId");

                    b.HasIndex("LinkedDataId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFeedback");
                });

            modelBuilder.Entity("SensoreApp.Models.SensorData", b =>
                {
                    b.HasOne("SensoreApp.Models.User", "User")
                        .WithMany("SensorDataEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SensoreApp.Models.UserFeedback", b =>
                {
                    b.HasOne("SensoreApp.Models.SensorData", "LinkedData")
                        .WithMany()
                        .HasForeignKey("LinkedDataId");

                    b.HasOne("SensoreApp.Models.User", "User")
                        .WithMany("FeedbackEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedData");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SensoreApp.Models.User", b =>
                {
                    b.Navigation("FeedbackEntries");

                    b.Navigation("SensorDataEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
